### PR TITLE
Correctly parse unicode text.

### PR DESCRIPTION
**Pull request by madmiraal**

### CODE REVIEW

**Comment by fire** [comment]
Can you provide a test plan?

Like sample steps to test this code?

**Review by TGRCdev — APPROVED** [review]

**Comment by TGRCdev** [comment]
I wrote a test for this. It takes a UTF-8 test file, inserts it into an SQLite database, brings it back out, and stores the result in `result.txt`.

This is the result from the `master` branch:

image

This is the result after applying @madmiraal's `fix-unicode` branch:

image

The code looks good, and the test results speak for themselves. I'm comfortable merging this.

Here's the test project if you want to run it yourself.
[SQLite Unicode.zip](https://github.com/godot-extended-libraries/godot-sqlite/files/4333568/SQLite.Unicode.zip)

**Comment by TGRCdev** [comment]
@madmiraal Would you mind if I merged these changes into the GDNative plugin as well? (crediting you, of course)

**Comment by madmiraal** [comment]
@TGRCdev Please feel free to merge them.

**Pull request merged**
